# Generated by Django 2.0.3 on 2018-07-09 11:49

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0015_sitesettings_handle_stock_by_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='product-banners')),
                ('product_url', models.URLField()),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings')),
            ],
        ),
    ]
