# Generated by Django 2.0.3 on 2018-07-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0016_productbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
