# Generated by Django 2.0.3 on 2018-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0018_halloffame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbanner',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
