# Generated by Django 2.0.3 on 2018-07-16 15:24

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0019_auto_20180715_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='product-banners')),
                ('category_url', models.URLField(blank=True, null=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings')),
            ],
        ),
    ]
