# Generated by Django 2.0.3 on 2018-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0021_productcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcoupon',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
