# Generated by Django 2.0.3 on 2018-10-23 15:57

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0022_auto_20181023_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='hall-of-fame')),
                ('url', models.URLField(blank=True, null=True)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.SiteSettings')),
            ],
        ),
    ]
