# Generated by Django 2.0.3 on 2019-06-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0024_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
