# Generated by Django 2.0.3 on 2019-06-10 10:06

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0025_auto_20190610_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='career-pic'),
        ),
    ]
