# Generated by Django 2.0.3 on 2019-06-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0026_career_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='image',
        ),
    ]
