# Generated by Django 2.0.3 on 2018-07-10 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignUpload',
            new_name='CustomDesign',
        ),
    ]
