# Generated by Django 2.0.3 on 2018-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180710_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdesign',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
