# Generated by Django 2.0.3 on 2018-09-22 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180710_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Max 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('number_of_pieces', models.IntegerField()),
                ('upload_design', models.FileField(blank=True, upload_to='bulk-order-upload-design')),
                ('list_of_names', models.FileField(blank=True, upload_to='bulk-order-lon')),
                ('additional_description', models.TextField()),
                ('teeshood_designs_product', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BulkOrderColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BulkOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='order_color',
            field=models.ManyToManyField(to='core.BulkOrderColor'),
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='order_type',
            field=models.ManyToManyField(to='core.BulkOrderType'),
        ),
    ]
