# Generated by Django 2.0.3 on 2018-09-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180922_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkordercolor',
            old_name='order_color',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bulkordertype',
            old_name='order_type',
            new_name='name',
        ),
    ]
