# Generated by Django 2.0.3 on 2018-09-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180922_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkorder',
            name='order_color',
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='order_color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.BulkOrderColor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bulkorder',
            name='order_type',
        ),
        migrations.AddField(
            model_name='bulkorder',
            name='order_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.BulkOrderType'),
            preserve_default=False,
        ),
    ]
